# Site settings
title: Leonardo Rifeli
email: leonardorifeli@gmail.com
url: https://leonardorifeli.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Leonardo Rifeli - <a href="" target="">MIT License</a> -
  location: Contatos
  social: Around the Web
  credits: MIT License

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/leonardorifeli
  - title: facebook
    url: https://www.facebook.com/leonardorifeli
  - title: github
    url: https://github.com/leonardorifeli

# Postal address (add as many lines as necessary)
address:
  - line: leonardorifeli@gmail.com
  - line: leonardorifeli@logatti.edu.br

# Credits content
credits: 'teste123'

# Build settings
markdown: kramdown
permalink: pretty
